-- ╭──────────────────────────────────────────────────────────╮
-- │          Copyright (c) 2022-present Lalit Kumar          │
-- │                       License: MIT                       │
-- ╰──────────────────────────────────────────────────────────╯

require("fluorite/plugins/barbar")
require("fluorite/plugins/bufferline")
require("fluorite/plugins/coc")
require("fluorite/plugins/fidget")
require("fluorite/plugins/gitgutter")
require("fluorite/plugins/gitsigns")
require("fluorite/plugins/hop")
require("fluorite/plugins/indent-blankline")
require("fluorite/plugins/leap")
require("fluorite/plugins/lightspeed")
require("fluorite/plugins/lir")
require("fluorite/plugins/lualine")
require("fluorite/plugins/marks")
require("fluorite/plugins/neo-tree")
require("fluorite/plugins/neogit")
require("fluorite/plugins/notify")
require("fluorite/plugins/nvim-cmp")
require("fluorite/plugins/nvim-fFHighlight")
require("fluorite/plugins/nvim-hlslens")
require("fluorite/plugins/nvim-lsp")
require("fluorite/plugins/nvim-lsp-installer")
require("fluorite/plugins/nvim-tree")
require("fluorite/plugins/nvim-treesitter")
require("fluorite/plugins/nvim-ts-rainbow")
require("fluorite/plugins/package-info")
require("fluorite/plugins/packer")
require("fluorite/plugins/startify")
require("fluorite/plugins/telescope")
require("fluorite/plugins/trouble")
require("fluorite/plugins/which-key")
require("fluorite/plugins/yanky")
